name: uShop
depends: [ Vault ]
softdepend: [ Essentials, PlaceholderAPI ]
authors: [ Linus122, KaspianDev ]
main: xyz.spaceio.ushop.Main
version: 2.3.0
api-version: 1.13
description: Sell your items easily
commands:
  ushop:
    description: Main command of ushop
    usage: /<command>
    permission: ushop.admin
